### ISSUE TITLE
fachliche Validierung der Plugin Konfiguration

### ISSUE THREAD

**Issue by bseber** [coffeenet/coffeenet-frontpage#21]
Als CoffeeNet Anwender möchte ich mein Plugin richtig konfigurieren, damit ich das Plugin auf meiner Startseite auch verwenden kann und die Startseite keine kaputten Plugins enthält.

**Akzeptanzkriterien**:

* Plugin Konfiguration wird validiert
  * serverseitig
  * info: clientseitiges Feedback direkt bei Eingabe folgt irgendwann. ist nicht Teil dieser Story
* CoffeeNet Anwender bekommt Fehlermeldungen angezeigt
* Wenn die Validierung fehlschlägt, wird das Plugin nicht angelegt

**Beispiele**:

* Zahlen
  * maximaler Wert
  * minimaler Wert
* RSS Plugin
  * kann die URL als Feed gelesen werden?

**Comment by derTobsch** [comment]
Done.
